name: "Deploy"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy Static Site"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "index.html,assets/"
          target: "/var/www/health/client"
